version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/gradle"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "demoA"
      - "demoB"
      - "demoC"
      - "dependabotKotlinVersionUpgrades"
