name: "Pull Request Labeler"
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  
jobs:
  labeler:
    permissions: write-all
    #    permissions:
    #      contents: read
    #      pull-requests: write
    #      actions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true
      - name: config git
        run: |
          git config --local user.email "1439809+joergi@users.noreply.github.com"
          git config --local user.name "Joergi via GitHub Actions"
      - name: empty commit
        if: success() || failure()
        run: |
          git co ${{ github.head_ref }}
          git pull
          git commit --allow-empty -m "trigger GitHub actions"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}

