name: "Pull Request Labeler"
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true
      - name: list runs
        run: |
          gh workflow run "Test Demo A"
          gh workflow run "Test Demo B"
          gh workflow run "Test Demo C"
        env:
          GH_TOKEN: ${{ github.token }}


