name: "Pull Request Labeler"
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  
jobs:
  labeler:
    permissions: write-all
    #    permissions:
    #      contents: read
    #      pull-requests: write
    #      actions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true
      - name: restart workflow Test Demo A
        run: gh workflow run testing-demoA.yml --ref ${{ github.head_ref }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - name: restart workflow Test Demo B
        run: gh workflow run testing-demoB.yml --ref ${{ github.head_ref }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - name: restart workflow Test Demo C
        run: gh workflow run testing-demoC.yml --ref ${{ github.head_ref }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - name: read all labels
        run: echo "${{ toJSON(github.event.pull_request.labels.*.name) }}"

