name: "Pull Request Labeler"
on:
  pull_request:
    branches: [ main ]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@4.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

