name: Enables auto-merge on dependency pull requests
"on":
  pull_request:
    branches:
      - main
    paths:
      - 'demoA/**'
      - 'demoB/**'
      - 'demoC/**'
  workflow_dispatch: {}
concurrency: ${{ github.workflow }}
jobs:
  enable-automerge:
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependabotKotlinVersionUpgrades')
      && (
        contains(github.event.pull_request.labels.*.name, 'minor')
        || contains(github.event.pull_request.labels.*.name, 'patch')
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}