name: Test DemoB

on:
  pull_request:
    paths:
      - 'demoB/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-demo-B:

    defaults:
      run:
        working-directory: ./demoB

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
        env:
          DEPLOY_ENV: qa
      - run: ./gradlew clean test
