name: Test Demo A

on:
  pull_request:
    paths:
      - 'demoA/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-demo-A:

    defaults:
      run:
        working-directory: ./demoA

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
        env:
          DEPLOY_ENV: qa
      - run: ./gradlew clean test
