name: Test Demo C

on:
  pull_request:
    paths:
      - 'demoA/**'
      - 'demoB/**'
      - 'demoC/**'
    branches: [ main ]
  workflow_dispatch: {}


jobs:
  reads-labels:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: read all labels
        run: echo "${{ toJSON(github.event.pull_request.labels.*.name) }}"
  test-demo-C:
    permissions: write-all
    #    permissions:
    #      contents: read
    #      pull-requests: write
    #      actions: write

    if: |
      contains(github.event.pull_request.labels.*.name, 'demoC')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demoC

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
        env:
          DEPLOY_ENV: qa
      - run: ./gradlew clean test
